# Generated by Django 5.2.6 on 2025-09-13 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="Nome do filme", max_length=200)),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Nota de 1 a 5",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "duracao_em_segundos",
                    models.IntegerField(help_text="Duração em segundos"),
                ),
                (
                    "genero",
                    models.CharField(help_text="Gênero do filme", max_length=100),
                ),
                ("data_publicacao", models.DateField(help_text="Data de Publicação")),
            ],
            options={
                "ordering": ["-data_publicacao", "nome"],
            },
        ),
    ]
