# Generated by Django 5.2.6 on 2025-09-23 14:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do filme', max_length=200)),
                ('nota', models.DecimalField(decimal_places=1, help_text='Nota de 1 a 5', max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('duracao_em_horas', models.DecimalField(decimal_places=2, help_text='Duração em horas', max_digits=6)),
                ('genero', models.CharField(help_text='Gênero do filme', max_length=100)),
                ('data_publicacaolicacao', models.DateField(help_text='Data de Publicação')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_publicacaolicacao', 'nome'],
            },
        ),
    ]
