version: "3.9"

services:
  web:
    build: .
    container_name: django_filmes
    command: python site_filmes/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
